---
triple:          'arm64-apple-darwin'
binary-path:     producer_consumer
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003618, symSize: 0x2B8 }
  - { offsetInCU: 0x4D, offset: 0x4D, size: 0x8, addend: 0x0, symName: _g_num_prod, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x69, offset: 0x69, size: 0x8, addend: 0x0, symName: _g_num_prod_lock, symBinAddr: 0x100008008, symSize: 0x0 }
  - { offsetInCU: 0xBB, offset: 0xBB, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003618, symSize: 0x2B8 }
  - { offsetInCU: 0x13E, offset: 0x13E, size: 0x8, addend: 0x0, symName: _producer_routine, symObjAddr: 0x2B8, symBinAddr: 0x1000038D0, symSize: 0x2CC }
  - { offsetInCU: 0x1BA, offset: 0x1BA, size: 0x8, addend: 0x0, symName: _consumer_routine, symObjAddr: 0x584, symBinAddr: 0x100003B9C, symSize: 0x178 }
...
